module.exports = {
	ADD_FAVORITE: 'ADD_FAVORITE',
	REMOVE_FAVORITE: 'REMOVE_FAVORITE',
	SET_ACTIVE_LOCATION: 'SET_ACTIVE_LOCATION',
	LOCATIONS_FAILED: 'LOCATIONS_FAILED',
	UPDATE_LOCATIONS: 'UPDATE_LOCATIONS'
}
